#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

$app = new Application('Sass Partial Manager', '1.0.6');

$app->add(new Spc\MakePartialCommand());

$app->run();
